---
version: "3.7"
services:
  air:
    build:
      context: ../
      dockerfile: dev/Dockerfile
    image: ngarindungu/rails-dev
    entrypoint: ["/bin/bash", "dev/entrypoint.sh"]
    command: "bundle exec rake"
    working_dir: /home/dev/active_interaction_rails
    volumes:
      - ../:/home/dev/active_interaction_rails
      - bundle:/usr/local/bundle

volumes:
  bundle:
